provider "github" {
  owner = "pbkn" #github id
  #authentication provided via Terraform Cloud env variable
}

resource "github_repository" "terraform-github-template" {
  name        = "terraform-github-template"
  description = "template repository create by terraform"
  visibility = "public"
}

resource "github_branch_protection" "terraform-github-template-main" {
  repository_id = github_repository.terraform-github-template.node_id #calling an autogenerated id param from repo creation
  pattern          = "main"
  enforce_admins   = true
  allows_deletions = false
}